-- Schema para Supabase (PostgreSQL)

-- Configurações do App (Armazena JSON de config e modules)
CREATE TABLE IF NOT EXISTS app_settings (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category VARCHAR(50) NOT NULL UNIQUE, -- 'config', 'modules'
  data JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Usuários
CREATE TABLE IF NOT EXISTS users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  usuario VARCHAR(80) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL, -- Em produção, usar auth do Supabase é melhor, mas mantendo compatibilidade
  papel VARCHAR(40) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE
);

-- Quartos / Mesas
CREATE TABLE IF NOT EXISTS rooms (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  whatsapp_principal VARCHAR(20),
  whatsapp_principal_index INT,
  status VARCHAR(40),
  hospedes JSONB DEFAULT '[]'::jsonb, -- Lista de hóspedes
  check_in DATE,
  check_out DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE
);

-- Estoque
CREATE TABLE IF NOT EXISTS inventory (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(140) NOT NULL,
  categoria VARCHAR(80),
  preco DECIMAL(10,2) NOT NULL DEFAULT 0,
  estoque INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE
);

-- Pedidos
CREATE TABLE IF NOT EXISTS orders (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quarto VARCHAR(100),
  local_entrega VARCHAR(100),
  status VARCHAR(40) NOT NULL DEFAULT 'pendente',
  itens JSONB DEFAULT '[]'::jsonb,
  horario TIMESTAMP WITH TIME ZONE,
  finalizado BOOLEAN DEFAULT FALSE,
  total DECIMAL(10,2) DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE
);

-- Vendas
CREATE TABLE IF NOT EXISTS sales (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  itens JSONB DEFAULT '[]'::jsonb,
  total DECIMAL(10,2) DEFAULT 0,
  forma_pagamento VARCHAR(50),
  quarto VARCHAR(100),
  comprador_nome VARCHAR(120),
  comprador_whatsapp VARCHAR(20),
  origem VARCHAR(40),
  data TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE
);

-- Transações
CREATE TABLE IF NOT EXISTS transactions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('receita', 'despesa')),
  categoria VARCHAR(50),
  descricao VARCHAR(255),
  valor DECIMAL(10,2) NOT NULL DEFAULT 0,
  data DATE NOT NULL,
  forma_pagamento VARCHAR(50),
  status VARCHAR(20) DEFAULT 'confirmado',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE
);

-- Eventos
CREATE TABLE IF NOT EXISTS events (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(160) NOT NULL, -- 'titulo' no schema antigo, 'nome' no json
  descricao TEXT,
  data DATE,
  hora_inicio VARCHAR(10),
  hora_fim VARCHAR(10),
  local VARCHAR(100),
  capacidade INT,
  participantes JSONB DEFAULT '[]'::jsonb,
  tipo VARCHAR(50),
  status VARCHAR(20),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE
);

-- Chat
CREATE TABLE IF NOT EXISTS chat (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text TEXT NOT NULL,
  from_name VARCHAR(120),
  from_sector VARCHAR(50),
  to_sector VARCHAR(50),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE
);

-- Seed inicial (Executar apenas se as tabelas estiverem vazias)
INSERT INTO app_settings (category, data) VALUES 
('config', '{"calendarSummary": "Eventos", "kitchenAvgMinutes": 25}'::jsonb),
('modules', '{"pms": true, "pdv": true, "estoque": true, "eventos": true, "financeiro": true, "restaurante": true}'::jsonb)
ON CONFLICT (category) DO NOTHING;

INSERT INTO users (nome, usuario, senha, papel) VALUES
('Administrador', 'admin', 'admin', 'administrador')
ON CONFLICT (usuario) DO NOTHING;
